### ISSUE TITLE
Do not expose ringsize

### ISSUE THREAD

**Issue by pinkbrad** [XMRWallet/Website#1]
Setting ringsize like MyMonero is dangerous. Look at the blockchain you can see many suspicious links because people will select high 41 ringsize and make multiple transaction.

I suggest making it advanced/custom only. Make the user input a size and hide it behind a big scary warning. It is almost never needed to use custom ring size.

**Comment by nathroy** [comment]
Thank you for your suggestion. I followed your advice.
Ring size feature was completely removed in the new commit and defaulted to 7. Will add an advanced feature in the future for members who understand its concept.
