### ISSUE TITLE
Error when attempting to "send"

### ISSUE THREAD

**Issue by bigrob69** [XMRWallet/Website#11]
"No Available Outputs" popup is received when attempting to transfer to another wallet.

**Comment by veteranxxx** [comment]
i have tried to use official wallet, but balance 0 :((( Are it;s the same with you? I think its scam :(((((

**Comment by bigrob69** [comment]
I have not yet tried the official. Where did you get it ? Do you also receive "No available outputs" on the site?

**Comment by veteranxxx** [comment]
I have tried all other wallets and my balance absolutely zero and in xmrwallet.com also receive "No available outputs" I think it's scam. I think I will give it to internet fraud police becoz I have lost a lot of money.

**Comment by veteranxxx** [comment]
it's scam :((((

**Comment by YnotLiveLyfe** [comment]
Hi guys,

    I just recovered my coin from XMRWallet.com.  Id like to help you if you haven gotten yours out yet.  My email is My username @gmail.  Send me a email and i can try to walk you through the process.

It took me all night but i finally have access to my coins again.

**Comment by nathroy** [comment]
Please excuse the late reply. The "No Available Outputs" error has been fixed, please try again. As for your comment "veteranxxx" we had issues syncing the blockchain which could have shown a zero balance by mistake. If for any reason you have difficulties accessing your wallet with my website, you can always sync your wallet using the core software from getmonero.org.
