### ISSUE TITLE
error when sending coins

### ISSUE THREAD

**Issue by veteranxxx** [XMRWallet/Website#12]
no outputs when sending. be aware scam!!!!

**Comment by YnotLiveLyfe** [comment]
Hi,

    I just recovered my coin from XMRWallet.com.  Id like to help you if you haven gotten yours out yet.  My email is My username @gmail.  Send me a msg so i can help

**Comment by nathroy** [comment]
Please excuse the late reply. The "No Available Outputs" error has been fixed, please try again.
