### ISSUE TITLE
project is a scam dont use it!!!!!

### ISSUE THREAD

**Issue by veteranxxx** [XMRWallet/Website#13]
Admin and support not responding to any issue, project is a scam!!!! If you send money to this wallet you will lost your coins :(

**Comment by YnotLiveLyfe** [comment]
Hi,

    I just recovered my coin from XMRWallet.com.  Id like to help you if you haven gotten yours out yet.  My email is My username @gmail.  Send me a msg so i can help

**Comment by nathroy** [comment]
Please excuse the late reply. We had issues syncing the blockchain which could have shown a zero balance by mistake. If for any reason you have difficulties accessing your wallet with my website, you can always sync your wallet using the core software from getmonero.org.
