### ISSUE TITLE
XMRWallet is not syncing. 

### ISSUE THREAD

**Issue by Tooniecoin** [XMRWallet/Website#22]
Will not retrieve funds sent to wallet. Been down for week.

**Comment by grugel-maintro** [comment]
PLS Fix this. My wallet is stuck at Height (13xxxxx/2518280) with syncing for days.

**Comment by Tooniecoin** [comment]
It appears that Malwarebytes is blocking the program
      on desktop computer? No syncing to obtain send funds.
      This started about a week ago.
      
    
    Contact:
SmokeSignal | Ron Mason
Mailing Address: P.O. Box 247,
Waterloo, Ontario N2J 3Z6

Tel & Fax: 1-866-517-6390
***@***.***
    On 2021-12-19 8:50 a.m., grugel-maintro
      wrote:
    
    
      
      PLS Fix this. My wallet is stuck at Height
        (13xxxxx/2518280) with syncing for days.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/XMRWallet/Website/issues/22#issuecomment-997395613",
"url": "https://github.com/XMRWallet/Website/issues/22#issuecomment-997395613",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by daddy699898** [comment]
mine has been not syncing either please fix

**Comment by nathroy** [comment]
Sync issues have been fixed for quite some time now.
