### ISSUE TITLE
This wallet took 1060XMR from me.

### ISSUE THREAD

**Issue by Lokanus** [XMRWallet/Website#23]
I tried to send a transaction of 300XMR out to swap for ethereum. While the confirm screen said 300XMR, it sent out my entire 1060XMR.

The website will not provide you with private tx keys so you cant see where its sent, if its even sent to the provided address.

i emailed support please respond to me ASAP

EDIT:
I got this as response:

"Hi Lok,

We are currently in stages of development for this feature and subaddresses.

It will be displayed next to each transaction to display verification.

My estimated development time is one month.

If you need it sooner, you can always import your seed into the Monero CLI and restore your wallet from there.

Hope that helps.

Regards,

Nathalie
XMRWallet.com"
_______________

They probably stole 1000 XMR from me, while i only wanted to send 300XMR. Refusing to give private tx keys. If i dont get refunded or the funds where not sent to the address i put in i will inform the FBI on this matter as this is a felony crime.

**Comment by nathroy** [comment]
This was discussed in the email, we have nothing to do with your loss of funds. We are still working on implementing the tx keys verify sequence. Thank you
