### ISSUE TITLE
Failed to create transaction (TypeError: outputs[i].tx_rct.ecdhInfo is undefined)

### ISSUE THREAD

**Issue by verymanley** [XMRWallet/Website#9]
Failed to create transaction (TypeError: outputs[i].tx_rct.ecdhInfo is undefined)

Error received after trying to send xmr

**Comment by YnotLiveLyfe** [comment]
I can Help you. Please contact me via email.  Its my username @gmail

**Comment by nathroy** [comment]
Please excuse the late reply. This issue has been resolved.
